trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: UsePythonVersion@0
  displayName: 'Using Python Version 3.10'
  inputs:
    versionSpec: '3.10'

- task: PublishCodeCoverageResults@1
  inputs:
    codeCoverageTool: Cobertura
    summaryFileLocation: '$(System.DefaultWorkingDirectory)/**/coverage.xml'

- task: PublishTestResults@2
  condition: succeededOrFailed()
  inputs:
    testResultsFiles: '**/test-*.xml'
    testRunTitle: 'Publish test results for Python 3.10'

- script: |
    pip install pytest pytest-azurepipelines
    pip install pytest-cov
    pip install customtkinter
    pip install youtube-search-python
    pip install pillow
  displayName: 'pytest'
    print('Hello')